# Generated by Django 5.2.12 on 2026-03-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_alter_event_options_remove_event_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrationfield",
            name="is_system",
            field=models.BooleanField(default=False),
        ),
    ]
