# Generated by Django 5.2.12 on 2026-03-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_registrationfield_is_system"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="public_id",
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
    ]
