# Generated by Django 5.2.12 on 2026-03-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_event_public_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="registration_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="registrations_closed",
            field=models.BooleanField(default=False),
        ),
    ]
