# Generated by Django 5.2.12 on 2026-03-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_event_registration_deadline_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tickettype",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
