# Generated by Django 5.2.12 on 2026-03-21 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_tickettype_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="checked_in",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="registration",
            name="checked_in_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
