# Generated by Django 5.2.12 on 2026-03-21 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_registration_checked_in_registration_checked_in_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="category",
            field=models.CharField(
                choices=[
                    ("all", "All Events"),
                    ("technology", "Technology"),
                    ("music", "Music"),
                    ("wellness", "Wellness"),
                    ("arts", "Arts & Culture"),
                    ("business", "Business"),
                    ("education", "Education"),
                    ("food", "Food & Drink"),
                    ("normal", "Event"),
                ],
                default="normal",
                max_length=20,
            ),
        ),
    ]
